---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: medusa-backend
  template:
    metadata:
      labels:
        name: medusa-backend
    spec:
      containers:
        - name: application
          image: username/medusa-backend
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dockerhub-secret
          # Temporarily use raw values for setting database credentials as environment variables, should use Secret management tool like Vault to store these secrets
          env:
            - name: POSTGRES_DB
              value: medusa-store
            - name: POSTGRES_USER
              value: donald
            - name: POSTGRES_PASSWORD
              value: le
            - name: POSTGRES_HOST
              value: postgresql:5432
          ports:
            - containerPort: 8081