---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-backend
spec:
  selector:
    matchLabels:
      name: medusa-backend
  template:
    metadata:
      labels:
        name: medusa-backend
    spec:
      containers:
        - name: application
          image: cuongld2/medusa-backend
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dockerhub-secret
          # Temporarily use raw values for setting database credentials as environment variables, should use Secret management tool like Vault to store these secrets
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: DATABASE_URL
              value: postgres://donald:le@postgresql:5432/medusa-store
            - name: JWT_SECRET
              value: something
            - name: COOKIE_SECRET
              value: something
            - name: DATABASE_TYPE
              value: postgres
            - name: STORE_CORS
              value: /http:\/\/*/
          ports:
            - containerPort: 9000