---
apiVersion: v1
kind: Service
metadata:
  name: medusa-backend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    name: medusa-backend